// dsh-notifier src/admin/ui/strings.mjs
// 管理台文案单一真相表（Issue #37 Admin Console i18n）。lang: 'zh'（默认）| 'en'。
// 未知值一律回落 zh（与 src/strings.mjs 同法；own-property 校验防 `__proto__` 继承键命中）。
//
// 结构（ADMIN_ZH 与 ADMIN_EN 必须逐键同形状，由 test/admin-ui-i18n.test.mjs 递归校验）：
//  - lang  ：写入 <html lang> 的值（zh-CN / en）
//  - title ：写入 <title> 的值
//  - markup：服务端骨架（ui/markup.mjs）用到的全部用户可见文案（纯字符串）
//  - client：浏览器脚本（ui/client.mjs）用到的全部用户可见文案（纯字符串，可含 {name} 占位）
//
// 重要：client 段经 safeJsonForInlineScript 内联进页面，JSON 序列化会丢弃函数，故本表
// 所有值必须是纯字符串（动态片段以 {占位} 表达，由浏览器端 tr(path, vars) 替换）。
// 文案值内不得出现反引号或 `${` 序列（会被内联脚本/测试模板字面量误解析）。

export const ADMIN_ZH = {
  lang: 'zh-CN',
  title: 'dsh-notifier 管理台',
  markup: {
    skip: '跳到主要内容',
    gateTitle: 'dsh-notifier 管理台',
    gateSub: '本机通知中枢 · 仅 127.0.0.1 回环可访问',
    gateNote: '输入插件启动时打印在终端的访问 token 进入管理台。',
    gateLabel: '访问 token',
    gatePlaceholder: '粘贴终端打印的 token',
    gatePeekAria: '显示或隐藏输入的 token',
    gatePeekShow: '显示',
    gateSubmit: '进入管理台',
    gateCancel: '取消',
    gateHint: 'token 首次启动时打印一次，此后只存哈希。遗失请删除 state 中的 <code>admin:token-hash</code> 后重启。token 仅存当前浏览器会话（sessionStorage），绝不写入 localStorage，关页即失效。',
    brandTitle: 'dsh-notifier 管理台',
    entryHint: '仅本机回环 · 当前入口：',
    btnCopyEntryTitle: '复制当前管理台地址',
    btnCopyEntry: '复制地址',
    tokenStateTitle: '点击输入或更换访问 token',
    btnLogoutTitle: '清除此浏览器会话中的访问 token',
    btnLogout: '退出',
    btnRefresh: '刷新',
    navAria: '主导航',
    tabDashboard: '首页',
    tabChannels: '通知渠道',
    tabMembers: '成员',
    tabNotify: '通知',
    tabBindings: '绑定矩阵',
    tabSessions: '会话',
    modeToggleTitle: '显示或隐藏高级会话与绑定设置',
    modeToggleOpen: '打开高级设置',
    setupTitle: '先把通知送到你手上',
    setupLead: '选渠道、填凭证、发一条真实测试通知，手机收到即完成。回复、审批、成员以后再说。',
    setupRailAria: '初始化进度',
    setupStep1: '选择渠道',
    setupStep2: '填写凭证',
    setupStep3: '测试送达',
    setupStep4: '完成',
    setupPickHint: '推荐选手机上已有的应用，更多渠道可展开。',
    setupFormHint: '带 * 为必填。保存后即可测试，无需重启。',
    setupBack2: '← 重选渠道',
    setupGoTest: '保存并发送测试通知',
    setupSaveOnly: '仅保存',
    setupBack3: '← 返回修改',
    setupRetest: '重新发送测试通知',
    setupDoneTitle: '测试通知已送达',
    setupDoneDetail: '通知链路已打通，此后 agent 通知会直接推送到该渠道。',
    setupFinish: '进入管理台首页',
    setupDoneChannels: '配置手机回复（可选）',
    setupDoneMembers: '配对成员（可选）',
    setupSkip: '稍后再说，先进管理台',
    setupFoot: 'YAML 仍可用于自动部署与高级配置，但不是默认路径',
    bannerTitle: '通知通道已在运行',
    bannerLead: '本浏览器还没验证过送达——发一条真实测试通知确认链路。',
    bannerTest: '发送测试通知',
    bannerDismiss: '我已确认可用',
    heroStateInit: '正在读取状态…',
    heroSub: '出站通知链路总览',
    heroRailAria: '运行状态进度',
    hstateUnconfigured: '未配置',
    hstateSaved: '已保存',
    hstateTested: '已测试',
    hstateReady: '正常运行',
    statActive: '活跃会话',
    statTotal: '会话总数',
    statKeys: 'agent 路由键',
    statMembers: '成员',
    outTitle: '出站通道',
    inTitle: '入站通道',
    inTitleHint: '手机远程控制（可选）',
    pendingTitle: '待处理远程提问',
    auditTitle: '最近审计',
    channelsLead: '在本页填好各渠道凭证即可。YAML 仅作为高级入口；未配置渠道在此页按字段配置。值为 *** 的字段视为未修改，提交时自动忽略。<b>出站通知</b>保存后即可测试，无需重启；<b>入站控制</b>为可选，配置后可在手机回复、审批。',
    membersLead1: '这里管理谁能远程操作（会话 / 审批 / 命令）。首位成员即 owner：负责生成、撤销配对码与角色分配，末位 owner 不可删。改号请在旧号发 /unpair、新号持码 /pair。',
    membersLead2: '个人模式默认：observe + approve 已开启；converse 可按需开启；群聊控制默认关闭。绑定矩阵与会话等高级设置默认隐藏，需要时点顶部「打开高级设置」。',
    mStatMembers: '成员',
    mStatOwners: 'owner',
    mStatPending: '待确认绑定',
    mGuided: '引导态：绑定表为空。宿主启动日志里有一枚引导配对码，任意通道私聊机器人发送 /pair &lt;码&gt; 即成为 owner（码随之作废）。',
    membersTableTitle: '成员表',
    thChannel: '渠道',
    thIdentity: '身份 id',
    thNote: '备注',
    thRole: '角色',
    thPairedAt: '配对时间',
    thLastSeen: '最近活跃',
    thActions: '操作',
    pairingTitle: '配对码',
    pairLabelPlaceholder: '备注（可选，≤64 字，核销时带上）',
    ttl10: '10 分钟',
    ttl30: '30 分钟',
    ttl60: '1 小时',
    ttl1440: '24 小时',
    btnMint: '生成配对码',
    thId: 'id',
    thOrigin: '来源',
    thState: '状态',
    thMintedAt: '铸造时间',
    thRemain: '剩余时效',
    pendingTableTitle: '待确认绑定',
    pendingLead: '扫码授权 / 订阅事件学到的身份（origin=learned）在此收口：确认即转正为成员，忽略即丢弃。',
    thFoundAt: '发现时间',
    notifyLead: '本页打开时可接收<b>系统桌面通知</b>（macOS 通知中心 / Windows Toast / Linux 通知服务），实时推送事件流。页面不可见时弹系统通知，可见时只进下方日志。偏好存在浏览器 localStorage。',
    nStatStream: '事件流',
    nStatPerm: '通知权限',
    nStatCount: '累计事件',
    streamInit: '未连接',
    permInit: '未知',
    btnPerm: '授权系统通知',
    btnTestNotify: '发送测试通知',
    npEnable: ' 总开关',
    npActive: ' 普通级也弹（关=仅紧急级）',
    npSound: ' 紧急级提示音',
    npHidden: ' 仅页面不可见时弹',
    notifyLogTitle: '事件日志（缓冲重放 + 实时，最多 50 条）',
    thTime: '时间',
    thLevel: '级别',
    thTitle: '标题',
    thBody: '正文 / 送达',
    thSource: '来源',
    emptyEvents: '暂无事件',
    bindingsLead: '出站 <b>route:agents</b>：键 = workspace 名（同项目多会话聚合），或精确 agentId（优先解析）。勾选该键的出站渠道；全不勾 = 该键出站静默（仍写账本）；删除行 = 删除整条绑定（回落全局渠道池）。「保存矩阵」全量保存。',
    thKey: '键（workspace / agentId）',
    thOutboundChecks: '出站渠道勾选',
    thQuiet: 'quiet',
    newKeyPlaceholder: '新增键：workspace 名或精确 agentId',
    btnAddKey: '新增键',
    defaultsTitle: '入站通道默认 agent（route:channels）',
    defaultsLead: '对话无显式 /bind 时，该通道消息默认投给此键；留空 = 不设置（回落唯一 agent &gt; 最近活跃）。',
    thInboundChannel: '入站通道',
    thDefaultAgent: '默认 agent（可下拉选现有键，也可自由输入）',
    btnSaveBindings: '保存矩阵',
    sessionsLead: 'route:sessions 会话台账：出站按「会话 diff → 精确 agentId → workspace → 全局渠道池」实时解析，覆盖层只存 diff。quiet 只静音出站推送，入站与审批永不被静音。',
    thWorkspace: 'workspace',
    thSession: '会话',
    thStatus: '状态',
    thResolved: '出站渠道（resolved）',
    thInboundHooks: '入站挂钩',
  },
  client: {
    // —— 基础 / 鉴权 ——
    loading: '加载中…',
    unknown: '(未知)',
    sourceSession: '会话 diff',
    sourceAgentExact: '精确 agentId',
    sourceAgentWorkspace: 'workspace',
    sourceGlobal: '全局渠道池',
    enterTokenEmpty: '请输入访问 token（终端首次启动时打印；遗失可删除 state 中的 admin:token-hash 后重启重新生成）',
    tokenSet: '会话 token 已设置（点击更换）',
    tokenUnset: '未设置 token（点击输入）',
    peekShow: '显示',
    peekHide: '隐藏',
    addressShownTop: '当前地址已显示在顶部，可手动复制',
    addressCopied: '管理台地址已复制',
    copyFailedShownTop: '复制失败：当前地址已显示在顶部，可手动复制',
    launchTicketInvalid: '启动票据无效或已过期',
    authReloginFailed: '鉴权失败：token 无效或已失效（已按一次自动重登录处理，请点击右上角 token 状态手动更新）',
    noTokenRetry: '未提供 token，点击右上角 token 状态重新输入',
    staleTokenRequest: '鉴权失败：该请求基于已失效的 token，请刷新后重试',
    loginCancelled: '登录已取消',
    authRetriedFailed: '鉴权失败：token 无效或已失效（已自动重试一次，请点击右上角 token 状态手动更新）',
    gateInvalidReason: 'token 无效或已失效，请重新输入（终端首次启动时打印；遗失可删除 state 中的 admin:token-hash 后重启重新生成）。',
    httpNotJson: 'HTTP {status}：响应不是 JSON',
    httpStatus: 'HTTP {status}',
    refreshed: '已刷新 {time}',
    loadFailed: '加载失败：{error}',
    modeOpen: '打开高级设置',
    modeClose: '关闭高级设置',
    // —— 首页英雄区 / 下一步 ——
    heroUnconfigured: '尚未配置通知渠道',
    heroReady: '通知链路正常',
    heroTested: '已验证送达 · 重启后并入投递',
    heroSaved: '已保存 · 待发送测试通知',
    heroSub: '出站 {enabled}/{total} 已启用 · 入站 {inbound} 已配置 · 成员 {members}',
    groupEnabled: '已启用（configured 且 enabled）',
    groupConfiguredDisabled: '已配置未启用',
    groupUnconfigured: '未配置',
    outNoneEmpty: '出站通道 {total} 个，均未配置（打开「通知渠道」页按字段配置；YAML 仅作为高级入口）',
    inConfigured: '已配置',
    inNoneEmpty: '（无入站通道）',
    noAudit: '暂无审计记录',
    nextSetupTitle: '第一步：配置一个通知渠道',
    nextSetupDesc: '在上方向导选择你手机上已有的应用，填入凭证并当场发送测试通知。',
    nextSetupBtn: '开始配置',
    nextTestTitle: '发送测试通知完成初始化',
    nextTestDesc: '保存成功不等于通知可达——发一条真实测试通知确认链路。',
    nextTestBtn: '去测试',
    nextMemberTitle: '可选：配对成员，启用手机远程控制',
    nextMemberDesc: '通知已可用。需要手机回复 / 审批 agent 时再去配对，不阻塞使用。',
    nextMemberBtn: '去成员页',
    nextReadyTitle: '一切就绪',
    nextReadyDesc: '通知链路已验证，成员已配对；agent 的通知会直接推送到你的设备。',
    // —— 首访向导 ——
    tilesNotLoaded: '渠道清单尚未加载（后端不可用或请求超时）。请点右上角「刷新」重试。',
    tileRecommended: '推荐',
    tileSaved: '已保存',
    tileMore: '全部 {total} 个渠道 →',
    tileMoreCollapse: '收起 ↑',
    fieldClear: '清除',
    fieldCleared: '已标记清除',
    setupFormTitle: '填写 {name} 凭证',
    setupDocLink: '官方接入文档 ↗',
    setupFormEmpty: '（该渠道暂无可编辑字段）',
    setupSavingConfig: '正在保存 {name} 配置…',
    btnSavingAndTesting: '保存并测试中…',
    btnSaving: '保存中…',
    btnSending: '发送中…',
    btnTesting: '测试中…',
    writeStateFailed: '写入失败：state 存储不可用（查看插件日志）',
    setupSaveOnlyDone: '配置已保存（state.json，0600）。保存成功不等于通知可达——点「保存并发送测试通知」当场验证；投递层在下次启动时并入运行时。',
    setupTesting: '配置已保存，正在向 {name} 发送真实测试通知…',
    setupTestSending: '正在发送测试通知…',
    deliveryReceipt: '送达回执：{detail}',
    testFailedRetry: '测试失败：{detail}。请检查必填凭证后重试，输入已保留。',
    channelReturnedFailure: '渠道返回失败',
    saveFailedRetry: '保存失败：{error}。可返回修改后重试，输入已保留。',
    saveFailed: '保存失败：{error}',
    setupPickChannel: '请先选择一个渠道',
    missingRequired: '必填字段未填写：{fields}',
    noChangedFields: '没有修改的字段（值为 *** 视为未修改，空值不提交），已跳过保存',
    setupDone: '初始化完成：通知链路已验证送达',
    // —— 验证横幅 ——
    bannerNoEnabled: '暂无已启用出站通道',
    bannerTestPassed: '测试通过：通知已送达 {type}',
    bannerTestFailed: '测试失败：{detail}；请到「通知渠道」页检查凭证后重试',
    // —— 远程提问 ——
    noPendingQuestions: '暂无待处理远程提问',
    qAdopt: '采用此项',
    qReject: '驳回（交还桌面处理）',
    qAgent: 'agent {agent}',
    qSource: '来源 {source}',
    qCreated: '创建 {time}',
    qExpires: '截至 {time}',
    qNoText: '(无文本)',
    qPendingBadge: '待决',
    qJoiner: '；',
    qSubmitting: '提交中…',
    qSettled: '已结算',
    qNotEffective: '未生效：{error}',
    // —— 绑定矩阵 ——
    bindNoOutbound: '（当前无出站通道可选）',
    quietTitle: '只静音出站推送（仍写账本）；入站与审批不受影响',
    delete: '删除',
    bindNoAgents: '尚无 agent 绑定（route:agents 为空）—— 所有会话出站回落全局渠道池',
    defaultAgentPlaceholder: '未设置：显式 bind &gt; 唯一 agent &gt; 最近活跃',
    bindNoInbound: '（无入站通道）',
    bindKeyRequired: '请输入键名（workspace 名或精确 agentId）',
    bindKeyExists: '键已存在：{key}',
    bindKeyAdded: '已加入编辑表（注意：全不勾渠道 = 显式空集 = 该键出站全静默）',
    bindKeyRemoved: '已从编辑表移除：{key}（点「保存矩阵」后整表生效）',
    bindingsSaved: '矩阵已保存（整表替换生效，未配置的会话即刻跟随新默认）',
    // —— 会话 ——
    quietFollow: 'quiet 跟随上游',
    quietOn: 'quiet 开（静音）',
    quietOff: 'quiet 关',
    sessionActive: '活跃',
    sessionGone: '已离场',
    sessionChannelsEmpty: '(空)',
    sessionChannelsJoiner: '、',
    sessionQuiet: '静音',
    sessionNormal: '正常',
    sessionEditOutbound: '编辑出站',
    sessionOverrideOutbound: '覆盖出站渠道',
    sessionPatchSave: 'PATCH 保存',
    sessionOverrideHint: '不勾「覆盖出站渠道」→ channels 发 null（删覆盖键，回落上游实时解析）；quiet 选「跟随上游」→ 发 null。',
    sessionEmpty: '尚无会话记录（route:sessions 为空；会话在 agent/created 时自动建档，出站回落全局渠道池）',
    sessionOverrideSaved: '会话出站覆盖已保存：{sid}',
    // —— 通道页 ——
    fieldReadonly: '只读字段',
    dirInbound: '入站',
    dirOutbound: '出站',
    badgeRestart: '重启后生效',
    badgeConfigured: '已配置',
    badgeUnconfigured: '未配置',
    scanAuth: '扫码授权',
    scanStopPolling: '停止轮询',
    scanStopped: '已停止轮询扫码状态',
    docOpen: '官方文档 ↗',
    docOpenTitle: '打开官方接入文档',
    wechatHint: '点「扫码授权」网页直接出二维码，用<b>你自己的微信</b>扫并确认：机器人会出现在你的微信好友里（专属好友，只和你聊），<b>扫码那一刻就完成配对</b>，不需要配对码。',
    testInbound: '连通性自检（出站）',
    testSend: '测试发送',
    readonlyHint: '只读：出站 webhook 走 YAML bootstrap（cordis.patch.yml channels）——{type}:account 键域归入站机器人凭证，网页写入会破坏扫码凭证',
    save: '保存',
    deleteConfig: '删除配置',
    cardEmptyFields: '（该通道暂无可编辑凭证键）',
    fieldHint: '值为 *** 的字段视为未修改，提交时自动剔除；带 * 为必填（空值不提交）。',
    testTitle: '验证该渠道的出站链路连通性（入站凭证是否可用需在 IM 端实际收发验证）',
    moreChannels: '更多 {count} 个渠道',
    moreChannelsHint: '点击展开完整清单',
    groupOutboundTitle: '出站通知',
    groupOutboundTag: '主',
    groupOutboundHint: '把 agent 的消息推送到你的设备（保存后可当场测试，无需重启）',
    groupInboundTitle: '入站控制',
    groupInboundTag: '可选',
    groupInboundHint: '手机远程回复 / 审批 agent；不配置不影响出站通知',
    noOutbound: '（无出站通道）',
    noInbound: '（无入站通道）',
    channelWriteFailed: '写入失败：state 存储不可用（查看插件日志）',
    channelSavedInbound: '凭证已保存（state.json，0600）；入站通道在插件下次启动时启用/重连。入站是否可用请在 IM 端实际发消息验证',
    channelSavedOutbound: '出站配置已保存（视图即时回显，重启后生效）：投递层在插件下次启动时并入运行时（YAML ⊕ store 合并），重启前不影响已运行的出站链路；可点「测试发送」立即验证凭证连通',
    testPassedNext: '测试通过{detail}；下一步：回首页确认运行状态，或直接开始使用',
    testFailedNext: '测试失败{detail}；下一步：检查必填凭证后重试',
    detailSuffix: '：{detail}',
    deleteInboundLabel: '入站凭证',
    deleteOutboundLabel: '出站配置',
    deleteConfirm: '删除 {type} 的{label}？立即生效且不可恢复（YAML 中的同名配置不受影响）。',
    deleted: '{type} 的{label}已删除',
    deleteFailed: '删除失败：{error}',
    scanCopy: '复制',
    scanOpenLink: '打开授权链接',
    scanOrCopy: '或复制内容贴到扫码工具',
    scanCopyHint: '复制上面的内容，贴到任意扫码工具完成授权',
    scanFailed: '扫码失败：{error}（可重新发起）',
    scanSaved: '授权完成，凭证已保存（通道在插件下次启动时启用/重连）',
    scanDone: '扫码流程已完成',
    scanWaiting: '等待扫码确认…（每 2 秒轮询一次）',
    scanAuthFailed: '扫码授权失败：{error}',
    copied: '已复制到剪贴板',
    copyFailed: '复制失败，请手动选择文本复制',
    clipboardUnavailable: '剪贴板不可用，请手动长按选择文本复制',
    // —— 成员页 ——
    expired: '已过期',
    remainHoursMinutes: '{h} 时 {m} 分',
    remainMinutesSeconds: '{m} 分 {s} 秒',
    remainPrefix: '剩余 {remain}',
    pairValidUntil: '有效期至 {time}（{remain}）——码面仅此一次展示，关闭后不可找回；发给用户私聊命令：/pair {code}',
    ttlHours: '{h} 小时内有效',
    ttlMinutes: '{m} 分钟内有效',
    pairMinted: '已铸造（id {id}）。{ttl}，单次核销。',
    pairMintFailed: '铸造失败：{error}',
    membersRefreshFailed: '成员数据刷新失败：{error}',
    labelPlaceholder: '备注',
    membersEmpty: '暂无成员。引导态下宿主启动日志（stderr）有引导码：用户私聊机器人发送 /pair &lt;码&gt; 即成首位 owner。',
    revoke: '撤销',
    pairCodesEmpty: '无在铸配对码。生成一枚发给要接入的成员（单次核销，过期作废）。',
    confirmPromote: '确认转正',
    dismiss: '忽略',
    pendingEmpty: '暂无待确认绑定（扫码/订阅学到的新身份会出现在这里）。',
    labelUpdated: '备注已更新',
    labelUpdateFailed: '备注更新失败：{error}',
    roleUpdated: '角色已更新',
    roleUpdateFailed: '角色更新失败：{error}',
    deleteMemberConfirm: '删除成员 {key}？该身份立即失去入站权限（运行中宿主半秒内生效）。',
    memberDeleted: '已删除成员 {key}',
    revokePairConfirm: '撤销配对码 {id}？该码将立即失效，且无法恢复。',
    pairRevoked: '已撤销配对码 {id}',
    revokeFailed: '撤销失败：{error}',
    memberConfirmed: '已确认转正 {key}',
    confirmFailed: '确认失败：{error}',
    dismissConfirm: '忽略待确认绑定 {key}？当前请求将被删除，之后需要对方重新触发订阅/扫码。',
    dismissed: '已忽略 {key}',
    opFailed: '操作失败：{error}',
    // —— 通知页 ——
    permGranted: '已授权',
    permDenied: '已拒绝',
    permUnsupported: '不支持',
    permDefault: '未授权',
    noTitle: '(无标题)',
    notifyAppName: 'dsh-notifier',
    noEvents: '暂无事件',
    deliveredConfirmed: '已确认送达 {channels}',
    deliveredAccepted: '已发送到提供方 {channels}',
    notDelivered: '未投递',
    failedChannelsSuffix: '（{count} 渠道失败）',
    replay: '重放',
    live: '实时',
    streamNoToken: '未设置 token，点击右上角 token 状态输入',
    streamOldSession: '旧会话请求已失效；当前 token 未受影响',
    streamConnected: '已连接',
    streamDisconnected: '已断开，5 秒后重连',
    streamTokenFailedRetry: 'token 失效（未重新登录，请点击右上角重试）',
    streamTokenFailedManual: 'token 失效（已自动重试一次，请刷新或点击右上角更新）',
    streamReloginReason: 'token 无效或已失效，请重新输入（终端首次启动时打印）。',
    notifyUnsupported: '此浏览器不支持系统通知',
    notifyTestTitle: 'dsh-notifier 测试',
    notifyTestBody: '如果你看到这条系统通知，桌面通知已就绪（{time}）',
    notifyTestFired: '已发起测试通知（权限未授权时只在浏览器内可见此提示）',
    logoutStream: '已退出本浏览器会话；点击 token 状态重新输入',
    logout: '已退出本浏览器会话',
    ticketOpened: '已通过 DSH 一次性启动票据打开高级管理台；敏感写操作仍使用原管理台会话鉴权。',
    launchInvalid: '启动链接中的凭证无效或已过期（链接仅在打印它的进程内有效）。请从终端重新复制 token 输入。',
    // —— 渠道清单（名称 / 一句话描述 / 是否推荐）——
    channelMeta: {
      bark: { name: 'Bark', tagline: 'iPhone 原生推送，一个 URL 即通', rec: true },
      telegram: { name: 'Telegram', tagline: 'Bot 推送到手机与桌面', rec: true },
      feishu: { name: '飞书', tagline: '群机器人 webhook 推送', rec: true },
      dingtalk: { name: '钉钉', tagline: '群机器人 webhook 推送', rec: true },
      wxpusher: { name: 'WxPusher', tagline: '微信服务通知推送', rec: true },
      pushplus: { name: 'PushPlus', tagline: '微信公众号消息推送', rec: false },
      serverchan: { name: 'Server酱', tagline: '微信方糖推送', rec: false },
      'wecom-app': { name: '企业微信应用', tagline: '企业微信应用消息', rec: false },
      'qq-bot': { name: 'QQ 机器人', tagline: 'QQ 单聊 / 群聊推送', rec: false },
      webhook: { name: 'Webhook', tagline: 'POST JSON 到自定义地址', rec: false },
      desktop: { name: '桌面通知', tagline: '本机系统通知弹窗', rec: false },
      bell: { name: '终端响铃', tagline: '本机终端提示音', rec: false },
      slack: { name: 'Slack', tagline: 'Slack webhook 推送', rec: false },
      discord: { name: 'Discord', tagline: 'Discord webhook 推送', rec: false },
      wecom: { name: '企业微信机器人', tagline: '群机器人 webhook 推送', rec: false },
      ntfy: { name: 'ntfy', tagline: '开源推送服务', rec: false },
      gotify: { name: 'Gotify', tagline: '自托管推送服务', rec: false },
      pushover: { name: 'Pushover', tagline: '多平台推送服务', rec: false },
      chanify: { name: 'Chanify', tagline: 'iOS 推送', rec: false },
      pushdeer: { name: 'PushDeer', tagline: '自托管推送', rec: false },
      mattermost: { name: 'Mattermost', tagline: 'Mattermost webhook', rec: false },
      gchat: { name: 'Google Chat', tagline: 'Google Chat webhook', rec: false },
      teams: { name: 'Teams', tagline: 'Microsoft Teams webhook', rec: false },
      xizhi: { name: '息知', tagline: '微信息知推送', rec: false },
      qmsg: { name: 'Qmsg', tagline: 'Qmsg 酱推送', rec: false },
      igot: { name: 'iGot', tagline: 'iGot 推送', rec: false },
      onebot: { name: 'OneBot', tagline: 'OneBot 协议推送', rec: false },
    },
  },
}

export const ADMIN_EN = {
  lang: 'en',
  title: 'dsh-notifier Admin Console',
  markup: {
    skip: 'Skip to main content',
    gateTitle: 'dsh-notifier Admin Console',
    gateSub: 'Local notification hub · reachable only on the 127.0.0.1 loopback',
    gateNote: 'Enter the access token printed to your terminal when the plugin starts.',
    gateLabel: 'Access token',
    gatePlaceholder: 'Paste the token printed in your terminal',
    gatePeekAria: 'Show or hide the entered token',
    gatePeekShow: 'Show',
    gateSubmit: 'Enter console',
    gateCancel: 'Cancel',
    gateHint: 'The token is printed once on first start; after that only its hash is stored. If lost, delete <code>admin:token-hash</code> from the state and restart. The token lives only in the current browser session (sessionStorage), never in localStorage, and expires when the page closes.',
    brandTitle: 'dsh-notifier Admin Console',
    entryHint: 'Loopback only · Current entry: ',
    btnCopyEntryTitle: 'Copy the current console address',
    btnCopyEntry: 'Copy address',
    tokenStateTitle: 'Click to enter or replace the access token',
    btnLogoutTitle: 'Clear the access token in this browser session',
    btnLogout: 'Sign out',
    btnRefresh: 'Refresh',
    navAria: 'Main navigation',
    tabDashboard: 'Dashboard',
    tabChannels: 'Channels',
    tabMembers: 'Members',
    tabNotify: 'Notifications',
    tabBindings: 'Binding matrix',
    tabSessions: 'Sessions',
    modeToggleTitle: 'Show or hide advanced session and binding settings',
    modeToggleOpen: 'Open advanced settings',
    setupTitle: 'Get a notification into your hands first',
    setupLead: 'Pick a channel, enter credentials, send one real test notification — done when your phone receives it. Replies, approvals and members can wait.',
    setupRailAria: 'Setup progress',
    setupStep1: 'Pick a channel',
    setupStep2: 'Enter credentials',
    setupStep3: 'Test delivery',
    setupStep4: 'Done',
    setupPickHint: 'Pick an app already on your phone; more channels can be expanded.',
    setupFormHint: 'Fields marked * are required. Test right after saving, no restart needed.',
    setupBack2: '← Pick another channel',
    setupGoTest: 'Save and send test notification',
    setupSaveOnly: 'Save only',
    setupBack3: '← Back to edit',
    setupRetest: 'Send test notification again',
    setupDoneTitle: 'Test notification delivered',
    setupDoneDetail: 'The notification path works; from now on agent notifications go straight to this channel.',
    setupFinish: 'Go to dashboard',
    setupDoneChannels: 'Configure phone replies (optional)',
    setupDoneMembers: 'Pair members (optional)',
    setupSkip: 'Later — take me to the console',
    setupFoot: 'YAML still works for automated deployment and advanced config, but it is not the default path',
    bannerTitle: 'Notification channel is already running',
    bannerLead: 'This browser has not verified delivery yet — send one real test notification to confirm the path.',
    bannerTest: 'Send test notification',
    bannerDismiss: 'I confirmed it works',
    heroStateInit: 'Reading status…',
    heroSub: 'Outbound notification path overview',
    heroRailAria: 'Running-state progress',
    hstateUnconfigured: 'Unconfigured',
    hstateSaved: 'Saved',
    hstateTested: 'Tested',
    hstateReady: 'Running',
    statActive: 'Active sessions',
    statTotal: 'Total sessions',
    statKeys: 'Agent routing keys',
    statMembers: 'Members',
    outTitle: 'Outbound channels',
    inTitle: 'Inbound channels',
    inTitleHint: 'Phone remote control (optional)',
    pendingTitle: 'Pending remote questions',
    auditTitle: 'Recent audit',
    channelsLead: 'Fill in each channel\'s credentials on this page. YAML is only an advanced entry; unconfigured channels are set up field by field here. Fields showing *** count as unchanged and are ignored on submit. <b>Outbound</b> can be tested right after saving, no restart; <b>inbound control</b> is optional and lets you reply and approve from your phone.',
    membersLead1: 'Manage who can operate remotely here (sessions / approvals / commands). The first member is the owner: they mint and revoke pairing codes and assign roles; the last owner cannot be removed. To switch numbers, send /unpair from the old one and /pair with a code from the new one.',
    membersLead2: 'Personal-mode defaults: observe + approve enabled; converse can be enabled on demand; group control is off by default. Advanced settings such as the binding matrix and sessions are hidden by default — click "Open advanced settings" at the top when needed.',
    mStatMembers: 'Members',
    mStatOwners: 'owner',
    mStatPending: 'Pending bindings',
    mGuided: 'Guided state: the binding table is empty. The host startup log contains a bootstrap pairing code — DM /pair &lt;code&gt; to the bot on any channel to become owner (the code is then void).',
    membersTableTitle: 'Members',
    thChannel: 'Channel',
    thIdentity: 'Identity id',
    thNote: 'Note',
    thRole: 'Role',
    thPairedAt: 'Paired at',
    thLastSeen: 'Last seen',
    thActions: 'Actions',
    pairingTitle: 'Pairing codes',
    pairLabelPlaceholder: 'Note (optional, ≤64 chars, carried at redemption)',
    ttl10: '10 minutes',
    ttl30: '30 minutes',
    ttl60: '1 hour',
    ttl1440: '24 hours',
    btnMint: 'Mint pairing code',
    thId: 'id',
    thOrigin: 'Origin',
    thState: 'State',
    thMintedAt: 'Minted at',
    thRemain: 'Time left',
    pendingTableTitle: 'Pending bindings',
    pendingLead: 'Identities learned from QR authorization / event subscription (origin=learned) are settled here: confirm promotes them to members, dismiss discards them.',
    thFoundAt: 'Found at',
    notifyLead: 'While this page is open it can show <b>system desktop notifications</b> (macOS Notification Center / Windows Toast / Linux notification service) from the live event stream. When the page is hidden it fires system notifications; when visible it only logs below. Preferences live in browser localStorage.',
    nStatStream: 'Event stream',
    nStatPerm: 'Notification permission',
    nStatCount: 'Total events',
    streamInit: 'Disconnected',
    permInit: 'Unknown',
    btnPerm: 'Grant system notifications',
    btnTestNotify: 'Send test notification',
    npEnable: ' Master switch',
    npActive: ' Also pop for normal level (off = urgent only)',
    npSound: ' Urgent-level sound',
    npHidden: ' Only pop when the page is hidden',
    notifyLogTitle: 'Event log (buffer replay + live, up to 50)',
    thTime: 'Time',
    thLevel: 'Level',
    thTitle: 'Title',
    thBody: 'Body / delivery',
    thSource: 'Source',
    emptyEvents: 'No events yet',
    bindingsLead: 'Outbound <b>route:agents</b>: key = workspace name (aggregates multiple sessions in the same project) or an exact agentId (resolved first). Check the outbound channels for that key; none checked = that key is silenced outbound (still logged); deleting a row = delete the whole binding (falls back to the global channel pool). "Save matrix" saves everything.',
    thKey: 'Key (workspace / agentId)',
    thOutboundChecks: 'Outbound channels',
    thQuiet: 'quiet',
    newKeyPlaceholder: 'New key: workspace name or exact agentId',
    btnAddKey: 'Add key',
    defaultsTitle: 'Inbound channel default agent (route:channels)',
    defaultsLead: 'With no explicit /bind, a channel\'s messages default to this key; empty = unset (falls back to the single agent &gt; most recent).',
    thInboundChannel: 'Inbound channel',
    thDefaultAgent: 'Default agent (pick an existing key or type freely)',
    btnSaveBindings: 'Save matrix',
    sessionsLead: 'route:sessions ledger: outbound resolves live as "session diff → exact agentId → workspace → global channel pool", and overlays store only the diff. quiet only silences outbound pushes; inbound and approvals are never silenced.',
    thWorkspace: 'workspace',
    thSession: 'Session',
    thStatus: 'Status',
    thResolved: 'Outbound channels (resolved)',
    thInboundHooks: 'Inbound hooks',
  },
  client: {
    // —— Base / auth ——
    loading: 'Loading…',
    unknown: '(unknown)',
    sourceSession: 'session diff',
    sourceAgentExact: 'exact agentId',
    sourceAgentWorkspace: 'workspace',
    sourceGlobal: 'global channel pool',
    enterTokenEmpty: 'Enter the access token (printed on first start; if lost, delete admin:token-hash from the state and restart to regenerate)',
    tokenSet: 'Session token set (click to replace)',
    tokenUnset: 'No token set (click to enter)',
    peekShow: 'Show',
    peekHide: 'Hide',
    addressShownTop: 'The current address is shown at the top; copy it manually',
    addressCopied: 'Console address copied',
    copyFailedShownTop: 'Copy failed: the current address is shown at the top; copy it manually',
    launchTicketInvalid: 'Launch ticket invalid or expired',
    authReloginFailed: 'Auth failed: token invalid or expired (one automatic re-login was attempted; click the token state at top right to update it manually)',
    noTokenRetry: 'No token provided; click the token state at top right to enter one',
    staleTokenRequest: 'Auth failed: this request used a stale token; refresh and retry',
    loginCancelled: 'Login cancelled',
    authRetriedFailed: 'Auth failed: token invalid or expired (already auto-retried once; click the token state at top right to update it manually)',
    gateInvalidReason: 'Token invalid or expired, please re-enter it (printed on first start; if lost, delete admin:token-hash from the state and restart to regenerate).',
    httpNotJson: 'HTTP {status}: response is not JSON',
    httpStatus: 'HTTP {status}',
    refreshed: 'Refreshed {time}',
    loadFailed: 'Load failed: {error}',
    modeOpen: 'Open advanced settings',
    modeClose: 'Close advanced settings',
    // —— Dashboard hero / next step ——
    heroUnconfigured: 'No notification channel configured yet',
    heroReady: 'Notification path is healthy',
    heroTested: 'Delivery verified · merged into delivery on restart',
    heroSaved: 'Saved · awaiting test notification',
    heroSub: 'Outbound {enabled}/{total} enabled · inbound {inbound} configured · members {members}',
    groupEnabled: 'Enabled (configured and enabled)',
    groupConfiguredDisabled: 'Configured, not enabled',
    groupUnconfigured: 'Unconfigured',
    outNoneEmpty: 'All {total} outbound channels are unconfigured (open the "Channels" page and set them up field by field; YAML is only an advanced entry)',
    inConfigured: 'Configured',
    inNoneEmpty: '(no inbound channels)',
    noAudit: 'No audit records yet',
    nextSetupTitle: 'Step 1: configure a notification channel',
    nextSetupDesc: 'Pick an app already on your phone in the wizard above, enter credentials, and send a test notification right there.',
    nextSetupBtn: 'Start setup',
    nextTestTitle: 'Send a test notification to finish setup',
    nextTestDesc: 'Saving is not the same as reachable — send a real test notification to confirm the path.',
    nextTestBtn: 'Go test',
    nextMemberTitle: 'Optional: pair members to enable phone remote control',
    nextMemberDesc: 'Notifications already work. Pair later when you need phone replies / agent approvals; it does not block usage.',
    nextMemberBtn: 'Go to members',
    nextReadyTitle: 'All set',
    nextReadyDesc: 'The notification path is verified and members are paired; agent notifications go straight to your devices.',
    // —— First-run wizard ——
    tilesNotLoaded: 'Channel list not loaded yet (backend unavailable or request timed out). Click "Refresh" at top right to retry.',
    tileRecommended: 'Recommended',
    tileSaved: 'Saved',
    tileMore: 'All {total} channels →',
    tileMoreCollapse: 'Collapse ↑',
    fieldClear: 'Clear',
    fieldCleared: 'Marked to clear',
    setupFormTitle: 'Enter {name} credentials',
    setupDocLink: 'Official setup docs ↗',
    setupFormEmpty: '(no editable fields for this channel)',
    setupSavingConfig: 'Saving {name} config…',
    btnSavingAndTesting: 'Saving and testing…',
    btnSaving: 'Saving…',
    btnSending: 'Sending…',
    btnTesting: 'Testing…',
    writeStateFailed: 'Write failed: state store unavailable (see plugin logs)',
    setupSaveOnlyDone: 'Config saved (state.json, 0600). Saving is not the same as reachable — click "Save and send test notification" to verify on the spot; the delivery layer merges into the runtime on next start.',
    setupTesting: 'Config saved; sending a real test notification to {name}…',
    setupTestSending: 'Sending the test notification…',
    deliveryReceipt: 'Delivery receipt: {detail}',
    testFailedRetry: 'Test failed: {detail}. Check the required credentials and retry; your input is kept.',
    channelReturnedFailure: 'channel returned failure',
    saveFailedRetry: 'Save failed: {error}. Go back to edit and retry; your input is kept.',
    saveFailed: 'Save failed: {error}',
    setupPickChannel: 'Please pick a channel first',
    missingRequired: 'Required fields missing: {fields}',
    noChangedFields: 'No changed fields (a value of *** counts as unchanged; empty values are not submitted), save skipped',
    setupDone: 'Setup complete: the notification path verified delivery',
    // —— Verify banner ——
    bannerNoEnabled: 'No enabled outbound channel',
    bannerTestPassed: 'Test passed: notification delivered via {type}',
    bannerTestFailed: 'Test failed: {detail}; check credentials on the "Channels" page and retry',
    // —— Remote questions ——
    noPendingQuestions: 'No pending remote questions',
    qAdopt: 'Adopt this',
    qReject: 'Reject (return to desktop)',
    qAgent: 'agent {agent}',
    qSource: 'source {source}',
    qCreated: 'created {time}',
    qExpires: 'expires {time}',
    qNoText: '(no text)',
    qPendingBadge: 'Pending',
    qJoiner: '; ',
    qSubmitting: 'Submitting…',
    qSettled: 'Settled',
    qNotEffective: 'No effect: {error}',
    // —— Binding matrix ——
    bindNoOutbound: '(no outbound channels to choose)',
    quietTitle: 'Only silences outbound pushes (still logged); inbound and approvals are unaffected',
    delete: 'Delete',
    bindNoAgents: 'No agent bindings yet (route:agents is empty) — all sessions fall back to the global channel pool outbound',
    defaultAgentPlaceholder: 'Unset: explicit bind &gt; single agent &gt; most recent',
    bindNoInbound: '(no inbound channels)',
    bindKeyRequired: 'Enter a key (workspace name or exact agentId)',
    bindKeyExists: 'Key already exists: {key}',
    bindKeyAdded: 'Added to the edit table (note: no channels checked = explicit empty set = that key is fully silenced outbound)',
    bindKeyRemoved: 'Removed from the edit table: {key} (takes effect after "Save matrix")',
    bindingsSaved: 'Matrix saved (whole-table replace takes effect; unconfigured sessions immediately follow the new defaults)',
    // —— Sessions ——
    quietFollow: 'quiet follows upstream',
    quietOn: 'quiet on (mute)',
    quietOff: 'quiet off',
    sessionActive: 'active',
    sessionGone: 'gone',
    sessionChannelsEmpty: '(empty)',
    sessionChannelsJoiner: ', ',
    sessionQuiet: 'muted',
    sessionNormal: 'normal',
    sessionEditOutbound: 'Edit outbound',
    sessionOverrideOutbound: 'Override outbound channels',
    sessionPatchSave: 'Save (PATCH)',
    sessionOverrideHint: 'Leave "Override outbound channels" unchecked → channels is sent as null (removes the override key, falls back to live upstream resolution); quiet "follows upstream" → sends null.',
    sessionEmpty: 'No sessions yet (route:sessions is empty; sessions are recorded on agent/created, outbound falls back to the global channel pool)',
    sessionOverrideSaved: 'Session outbound override saved: {sid}',
    // —— Channels ——
    fieldReadonly: 'read-only field',
    dirInbound: 'inbound',
    dirOutbound: 'outbound',
    badgeRestart: 'Takes effect after restart',
    badgeConfigured: 'Configured',
    badgeUnconfigured: 'Unconfigured',
    scanAuth: 'Scan to authorize',
    scanStopPolling: 'Stop polling',
    scanStopped: 'Stopped polling the QR status',
    docOpen: 'Official docs ↗',
    docOpenTitle: 'Open the official setup docs',
    wechatHint: 'Click "Scan to authorize" to get a QR code on the page, scan it with <b>your own WeChat</b> and confirm: the bot appears in your WeChat contacts (a dedicated friend only for you), and <b>pairing completes the moment you scan</b> — no pairing code needed.',
    testInbound: 'Connectivity self-check (outbound)',
    testSend: 'Send test',
    readonlyHint: 'Read-only: the outbound webhook uses YAML bootstrap (cordis.patch.yml channels) — the {type}:account key space belongs to the inbound bot credentials; writing from the web would break the scanned credentials',
    save: 'Save',
    deleteConfig: 'Delete config',
    cardEmptyFields: '(no editable credential keys for this channel)',
    fieldHint: 'Fields showing *** count as unchanged and are stripped on submit; fields marked * are required (empty values are not submitted).',
    testTitle: 'Verify this channel\'s outbound connectivity (whether inbound credentials work must be verified by actually sending/receiving in the IM app)',
    moreChannels: '{count} more channels',
    moreChannelsHint: 'Click to expand the full list',
    groupOutboundTitle: 'Outbound notifications',
    groupOutboundTag: 'Primary',
    groupOutboundHint: 'Push agent messages to your devices (testable right after saving, no restart)',
    groupInboundTitle: 'Inbound control',
    groupInboundTag: 'Optional',
    groupInboundHint: 'Reply to / approve the agent from your phone; leaving it unconfigured does not affect outbound notifications',
    noOutbound: '(no outbound channels)',
    noInbound: '(no inbound channels)',
    channelWriteFailed: 'Write failed: state store unavailable (see plugin logs)',
    channelSavedInbound: 'Credentials saved (state.json, 0600); the inbound channel is enabled/reconnected on the plugin\'s next start. Whether inbound works must be verified by actually sending a message in the IM app',
    channelSavedOutbound: 'Outbound config saved (view reflects immediately, takes effect after restart): the delivery layer merges into the runtime on the plugin\'s next start (YAML ⊕ store merge) and does not affect the already-running outbound path before then; click "Send test" to verify credential connectivity now',
    testPassedNext: 'Test passed{detail}; next: go to the dashboard to confirm the running state, or start using it now',
    testFailedNext: 'Test failed{detail}; next: check the required credentials and retry',
    detailSuffix: ': {detail}',
    deleteInboundLabel: 'inbound credentials',
    deleteOutboundLabel: 'outbound config',
    deleteConfirm: 'Delete {type} {label}? Takes effect immediately and cannot be undone (a same-named config in YAML is unaffected).',
    deleted: 'Deleted {type} {label}',
    deleteFailed: 'Delete failed: {error}',
    scanCopy: 'Copy',
    scanOpenLink: 'Open authorization link',
    scanOrCopy: 'or copy it into a QR tool',
    scanCopyHint: 'Copy the text above and paste it into any QR tool to complete authorization',
    scanFailed: 'Scan failed: {error} (you can start again)',
    scanSaved: 'Authorization complete; credentials saved (the channel is enabled/reconnected on the plugin\'s next start)',
    scanDone: 'Scan flow completed',
    scanWaiting: 'Waiting for scan confirmation… (polling every 2 seconds)',
    scanAuthFailed: 'Scan authorization failed: {error}',
    copied: 'Copied to clipboard',
    copyFailed: 'Copy failed, please select and copy the text manually',
    clipboardUnavailable: 'Clipboard unavailable, please long-press to select and copy the text manually',
    // —— Members ——
    expired: 'expired',
    remainHoursMinutes: '{h}h {m}m',
    remainMinutesSeconds: '{m}m {s}s',
    remainPrefix: 'Remaining {remain}',
    pairValidUntil: 'Valid until {time} ({remain}) — the code is shown only once and cannot be retrieved after closing; send the user the private-chat command: /pair {code}',
    ttlHours: 'valid for {h} hours',
    ttlMinutes: 'valid for {m} minutes',
    pairMinted: 'Minted (id {id}). {ttl}, single-use.',
    pairMintFailed: 'Mint failed: {error}',
    membersRefreshFailed: 'Failed to refresh member data: {error}',
    labelPlaceholder: 'Note',
    membersEmpty: 'No members yet. In guided state the host startup log (stderr) holds a bootstrap code: have the user DM /pair &lt;code&gt; to the bot to become the first owner.',
    revoke: 'Revoke',
    pairCodesEmpty: 'No pairing codes in circulation. Mint one for the member you want to onboard (single-use, expires).',
    confirmPromote: 'Confirm',
    dismiss: 'Dismiss',
    pendingEmpty: 'No pending bindings (new identities learned via scan/subscription appear here).',
    labelUpdated: 'Note updated',
    labelUpdateFailed: 'Note update failed: {error}',
    roleUpdated: 'Role updated',
    roleUpdateFailed: 'Role update failed: {error}',
    deleteMemberConfirm: 'Delete member {key}? That identity immediately loses inbound access (takes effect within half a second on a running host).',
    memberDeleted: 'Deleted member {key}',
    revokePairConfirm: 'Revoke pairing code {id}? It will become invalid immediately and cannot be restored.',
    pairRevoked: 'Revoked pairing code {id}',
    revokeFailed: 'Revoke failed: {error}',
    memberConfirmed: 'Confirmed {key}',
    confirmFailed: 'Confirm failed: {error}',
    dismissConfirm: 'Dismiss pending binding {key}? The current request will be deleted and the other side must trigger subscription/scan again.',
    dismissed: 'Dismissed {key}',
    opFailed: 'Operation failed: {error}',
    // —— Notifications ——
    permGranted: 'Granted',
    permDenied: 'Denied',
    permUnsupported: 'Unsupported',
    permDefault: 'Not granted',
    noTitle: '(no title)',
    notifyAppName: 'dsh-notifier',
    noEvents: 'No events yet',
    deliveredConfirmed: 'Delivery confirmed {channels}',
    deliveredAccepted: 'Sent to provider {channels}',
    notDelivered: 'Not delivered',
    failedChannelsSuffix: ' ({count} channels failed)',
    replay: 'replay',
    live: 'live',
    streamNoToken: 'No token set; click the token state at top right to enter one',
    streamOldSession: 'Old session request is stale; the current token is unaffected',
    streamConnected: 'Connected',
    streamDisconnected: 'Disconnected, reconnecting in 5s',
    streamTokenFailedRetry: 'Token invalid (not re-logged in; click top right to retry)',
    streamTokenFailedManual: 'Token invalid (already auto-retried once; refresh or click top right to update)',
    streamReloginReason: 'Token invalid or expired, please re-enter it (printed on first start).',
    notifyUnsupported: 'This browser does not support system notifications',
    notifyTestTitle: 'dsh-notifier test',
    notifyTestBody: 'If you see this system notification, desktop notifications are ready ({time})',
    notifyTestFired: 'Test notification triggered (visible in-browser only when permission is not granted)',
    logoutStream: 'Signed out of this browser session; click the token state to re-enter',
    logout: 'Signed out of this browser session',
    ticketOpened: 'Opened the advanced console via a one-time DSH launch ticket; sensitive writes still use the original console session auth.',
    launchInvalid: 'The credential in the launch link is invalid or expired (the link is only valid within the process that printed it). Please copy the token from the terminal and enter it again.',
    // —— Channel catalog (name / one-line description / recommended) ——
    channelMeta: {
      bark: { name: 'Bark', tagline: 'Native iPhone push, one URL and done', rec: true },
      telegram: { name: 'Telegram', tagline: 'Bot push to phone and desktop', rec: true },
      feishu: { name: 'Feishu', tagline: 'Group bot webhook push', rec: true },
      dingtalk: { name: 'DingTalk', tagline: 'Group bot webhook push', rec: true },
      wxpusher: { name: 'WxPusher', tagline: 'WeChat service-notification push', rec: true },
      pushplus: { name: 'PushPlus', tagline: 'WeChat official-account message push', rec: false },
      serverchan: { name: 'ServerChan', tagline: 'WeChat ServerChan push', rec: false },
      'wecom-app': { name: 'WeCom App', tagline: 'WeCom app messages', rec: false },
      'qq-bot': { name: 'QQ Bot', tagline: 'QQ private / group chat push', rec: false },
      webhook: { name: 'Webhook', tagline: 'POST JSON to a custom URL', rec: false },
      desktop: { name: 'Desktop notification', tagline: 'Local system notification popup', rec: false },
      bell: { name: 'Terminal bell', tagline: 'Local terminal chime', rec: false },
      slack: { name: 'Slack', tagline: 'Slack webhook push', rec: false },
      discord: { name: 'Discord', tagline: 'Discord webhook push', rec: false },
      wecom: { name: 'WeCom Bot', tagline: 'Group bot webhook push', rec: false },
      ntfy: { name: 'ntfy', tagline: 'Open-source push service', rec: false },
      gotify: { name: 'Gotify', tagline: 'Self-hosted push service', rec: false },
      pushover: { name: 'Pushover', tagline: 'Multi-platform push service', rec: false },
      chanify: { name: 'Chanify', tagline: 'iOS push', rec: false },
      pushdeer: { name: 'PushDeer', tagline: 'Self-hosted push', rec: false },
      mattermost: { name: 'Mattermost', tagline: 'Mattermost webhook', rec: false },
      gchat: { name: 'Google Chat', tagline: 'Google Chat webhook', rec: false },
      teams: { name: 'Teams', tagline: 'Microsoft Teams webhook', rec: false },
      xizhi: { name: 'Xizhi', tagline: 'WeChat Xizhi push', rec: false },
      qmsg: { name: 'Qmsg', tagline: 'Qmsg push', rec: false },
      igot: { name: 'iGot', tagline: 'iGot push', rec: false },
      onebot: { name: 'OneBot', tagline: 'OneBot protocol push', rec: false },
    },
  },
}

const TABLE = { zh: ADMIN_ZH, en: ADMIN_EN }

/** 按语言取管理台文案表；未知/缺失回落 zh。own-property 校验：避免继承键命中原型链。 */
export function adminStringsOf(lang) {
  return Object.prototype.hasOwnProperty.call(TABLE, lang) ? TABLE[lang] : ADMIN_ZH
}

/** HTML 文本/属性转义（服务端骨架对动态插值的唯一出口）。 */
export function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/** 安全内联 JSON：转义 `<`/`>`/`&` 与 U+2028/2029，杜绝 `</script` 提前闭合与行分隔符破句；
 *  非 ASCII（CJK）保持原样，便于本地化文案在 HTML 中可读且可被文本断言命中。 */
export function safeJsonForInlineScript(value) {
  return JSON.stringify(value)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}
